alias z='cd ~/works'

alias py='python'
alias py3='python3'
alias e='vim'

alias gc='git commit'
alias gch='git checkout'
alias gchm='git checkout master'
alias gp='git push'
alias gpo='git push origin'
alias gpom='git push origin master'
alias gs='git status'
alias ga='git add'
alias grm='git rm'
alias gcl='git clone'
alias gl='git log'
